In [1]:
import tensorflow as tf
print("Tensor flow:" ,tf.__version__)

Tensor flow: 2.20.0


In [8]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.

scalar = tf.constant(10)
print(f"scaler shape:{scalar.shape},values :{scalar.numpy()}")
print(f"\nScalar dtype :{scalar.dtype}")

scaler shape:(),values :10

Scalar dtype :<dtype: 'int32'>


In [9]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.

vector = tf.constant([1,2,3,4])
print(f"vector shape:{vector.shape},values :{vector.numpy()}")

vector shape:(4,),values :[1 2 3 4]


In [10]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix = tf.constant([[1,2],[3,4]])
print(f"matrix shape:{matrix.shape}")
print(f"\nMatrix dtype :{matrix.dtype}")

matrix shape:(2, 2)

Matrix dtype :<dtype: 'int32'>


In [12]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.

values = tf.Variable(([5.0]))
print("variable example")
print(f"current value:\n{values.numpy()}")

variable example
current value:
[5.]


In [14]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.

values.assign([10.0])
print(f"updated value:\n{values.numpy()}")


updated value:
[10.]


In [15]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

a= tf.constant([[1,2],[3,4]])
b= tf.constant([[1,1],[1,1]])

addition = tf.add(a,b)
print(f"addition:\n{addition.numpy()}")


addition:
[[2 3]
 [4 5]]


In [16]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().

a= tf.constant([[1,2],[3,4]])
b= tf.constant([[5,6],[7,8]])

mutmul = tf.matmul(a,b)

print(f"matrix multiplication:\n{mutmul.numpy()}")

matrix multiplication:
[[19 22]
 [43 50]]


In [18]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
tensor = tf.random.uniform(shape=(3, 3))
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Values:\n", tensor)


Shape: (3, 3)
Dtype: <dtype: 'float32'>
Values:
 tf.Tensor(
[[0.73165154 0.52803004 0.52953625]
 [0.7473085  0.9630774  0.11601436]
 [0.4954555  0.9145647  0.02024889]], shape=(3, 3), dtype=float32)
